FROM python:3.9-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip \
    && pip install --no-cache-dir ultralytics==8.3.0 kafka-python==2.0.2 pandas==2.2.2 opencv-python==4.9.0.80